import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import preprocess from 'svelte-preprocess';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const isProd = process.env.NODE_ENV === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source visit the plugins github repository
*/
`;

export default defineConfig({
  plugins: [
    svelte({
      emitCss: false,
      preprocess: preprocess({
        typescript: {
          compilerOptions: {
            target: 'ES2020',
            strict: false,
          },
        },
      }),
    }),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/main.ts'),
      name: 'main',
      fileName: 'main',
      formats: ['cjs'],
    },
    rollupOptions: {
      external: ['obsidian'],
      output: {
        banner,
        sourcemap: isProd ? false : 'inline',
        exports: 'default',
      },
    },
    target: 'es2020',
    sourcemap: isProd ? false : 'inline',
    minify: isProd,
  },
  define: {
    global: 'globalThis',
  },
});